TRUNCATE TABLE user RESTART IDENTITY;

TRUNCATE TABLE Pessoa RESTART IDENTITY;

TRUNCATE TABLE Professor RESTART IDENTITY;

TRUNCATE TABLE Administrador RESTART IDENTITY;

TRUNCATE TABLE Curriculo RESTART IDENTITY;

TRUNCATE TABLE Aluno RESTART IDENTITY;

TRUNCATE TABLE Disciplina RESTART IDENTITY;

TRUNCATE TABLE Ministra RESTART IDENTITY;

TRUNCATE TABLE Planeja RESTART IDENTITY;

TRUNCATE TABLE Oferecimento RESTART IDENTITY;

TRUNCATE TABLE Cursa RESTART IDENTITY;

TRUNCATE TABLE Trilha RESTART IDENTITY;

TRUNCATE TABLE Modulo RESTART IDENTITY;

TRUNCATE TABLE rel_dis_mod RESTART IDENTITY;

TRUNCATE TABLE Perfil RESTART IDENTITY;

TRUNCATE TABLE Servico RESTART IDENTITY;

TRUNCATE TABLE us_pf RESTART IDENTITY;

TRUNCATE TABLE pf_se RESTART IDENTITY;
