version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  postgres:
    image: "postgres:11.4"
    restart: always
    volumes:
    - ../acesso.sql:/docker-entrypoint-initdb.d/1-acesso.sql
    - ../pessoa.sql:/docker-entrypoint-initdb.d/2-pessoa.sql
    - ../acesso-pessoa.sql:/docker-entrypoint-initdb.d/3-acesso-pessoa.sql
